Update JuliaInterface buildsystem to latest Makefile.gappkg

diff --git a/pkg/JuliaInterface/configure b/pkg/JuliaInterface/configure
--- a/pkg/JuliaInterface/configure
+++ b/pkg/JuliaInterface/configure
@@ -4,11 +4,15 @@
 
 set -e
 
-if test -z "$1"; then
-  GAPPATH=../../..; echo "Using ../../.. as default GAP path";
-else
-  GAPPATH=$1;
-fi
+GAPPATH=../..
+while test "$#" -ge 1 ; do
+  option="$1" ; shift
+  case "$option" in
+    --with-gaproot=*) GAPPATH=${option#--with-gaproot=}; ;;
+    -*)               echo "ERROR: unsupported argument $option" ; exit 1;;
+    *)                GAPPATH="$option" ;;
+  esac
+done
 
 if test ! -r "$GAPPATH/sysinfo.gap" ; then
     echo
@@ -16,7 +20,7 @@ if test ! -r "$GAPPATH/sysinfo.gap" ; then
     echo
     echo "Usage: ./configure [GAPPATH]"
     echo "       where GAPPATH is a path to your GAP installation"
-    echo "       (The default for GAPPATH is \"../../..\")"
+    echo "       (The default for GAPPATH is \"../..\")"
     echo
     echo "Either your GAPPATH is incorrect or the GAP it is pointing to"
     echo "is not properly compiled (do \"./configure && make\" there first)."
@@ -27,17 +31,4 @@ if test ! -r "$GAPPATH/sysinfo.gap" ; then
 fi
 
 echo "Using settings from $GAPPATH/sysinfo.gap"
-
-. "$GAPPATH/sysinfo.gap"
-
-if test "x$JULIA_LIBS" = "x" ; then
-    echo "JULIA_LIBS not set in sysinfo.gap. Maybe your GAP version is too old"
-    exit 1
-fi
-
-sed \
-    -e "s;@GAPARCH@;$GAParch;g" \
-    -e "s;@GAPPATH@;$GAPPATH;g" \
-    -e "s;@JULIA_LDFLAGS@;$JULIA_LDFLAGS;g" \
-    -e "s;@JULIA_LIBS@;$JULIA_LIBS;g" \
-    Makefile.in > Makefile
+sed -e "s;@GAPPATH@;$GAPPATH;g" Makefile.in > Makefile
